### PR TITLE
fixes type restriction on input arguments and Improve docs

### PR DESCRIPTION
**Pull request by lazarusA**
This adds 3 main things

1. less restrictive type input arguments, no restrictions
2. improved documentation
3. YAXArray example with mapCube (for out of memory calculations)

I didn't and will not look at the auto formatting issues, please feel free to do so. CI or additional comments I would consider. This was a good sprint. Cheers!

### CODE REVIEW

**Comment by MartinuzziFrancesco** [comment]
should the documenter github action be removed? if not could you look into the cause of failure?

**Comment by lazarusA** [comment]
yeah, it looks like that's the issue. Apparently, I'm not up to date with deploy workflow. Let's see if it works now.

**Comment by MartinuzziFrancesco** [comment]
that did it apparently

**Comment by lazarusA** [comment]
the only thing missing is the formatter. How to you do it? what's the workflow to apply that. I usually don't enforce it, hence I'm not familiar with it.

**Comment by MartinuzziFrancesco** [comment]
I should have added an automatic formatter actually, I'm curios to see if it works. It should open a pr with the formatted code. If that doesn't work I'll just format myself

**Pull request merged**
